### ISSUE TITLE
Implement

### ISSUE THREAD

**Issue by kentcdodds** [formly-js/angular-formly-simplified#1]
@a-laughlin [mentioned](https://github.com/formly-js/angular-formly/issues/396) a need to simplify angular-formly's API for the common use-case. I agree with him. He's got an abstraction already that he's willing to open source. Thanks!

**Comment by a-laughlin** [comment]
Howdy, and thanks for the invite!

**Comment by a-laughlin** [comment]
Initial commit coming later this week.  [This bug](https://github.com/formly-js/angular-formly/issues/399) ended up costing me a lot more time than I expected to spend this last week.

**Comment by a-laughlin** [comment]
Hey Kent,

There are no "fork" or "clone" links in this repo.  Possibly a [permissions issue](https://help.github.com/articles/working-with-repositories/#forking)?  Can you check if I have sufficient permissions to push code up or fork/PR?

Thanks!

Adam

**Comment by a-laughlin** [comment]
Nevermind.  I was able to clone it using the base repo https:// address.

**Comment by a-laughlin** [comment]
And... can't push an initial commit.  Permission denied 403.  It looks like permissions may be an issue after all.

**Comment by kentcdodds** [comment]
Sorry, forgot to add the team. You should have it now.

**Comment by a-laughlin** [comment]
Code and comments added to the [initial file](https://github.com/formly-js/angular-formly-simplified/blob/master/angular-formly-simplified.js).

**Comment by kentcdodds** [comment]
Awesome! I look forward to looking into this when I get more time 👍

-Kent C. Dodds

**Comment by a-laughlin** [comment]
Refactored.  Works  better and simpler now.  Moved most of the comments into a README.
